services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job-match

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass jobmatch_redis_pass
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=jobmatch_redis_pass

volumes:
  redis_data: