logging:
  level:
    org:
      springframework:
        security: TRACE
  file:
    path: /logs/


spring:
  application:
    name: JobMatch

  # Internationalization Configuration
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600s
    fallback-to-system-locale: false
    use-code-as-default-message: true

  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: jobmatch_redis_pass
      timeout: 2000ms
      
  datasource:
    url: jdbc:postgresql://localhost:5432/job-match
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    # defer-datasource-initialization: true
  # sql:
  #   init:
  #     data-locations: classpath:/data.sql
  #     mode: always

jwt:
  secret-key: ${JWT_SECRET_KEY:7e28991c10c1f5294a74dbcab40b23d77a291c612692b97eb8f8c3d67c6d0e0507059122d8cb52b9ca009b214b83977cf4d4d7472d924c745102f1e18497df05}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:7200}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api/v3/api-docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
    doc-expansion: none
    default-models-expand-depth: 1
    default-model-expand-depth: 1
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  # Enable automatic generation of examples from validation annotations
  use-fqn: false
  # Automatically generate operation IDs
  auto-tag-classes: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:cloud_name}
  api-key: ${CLOUDINARY_API_KEY:api_key}
  api-secret: ${CLOUDINARY_API_SECRET:api_secret}